inputs:
  repo:
    required: true
  sha:
    required: true
  state:
    required: true
    type: choice
    options:
      - pending
      - success
      - error
      - failure
  description:
    required: true
  token:
    required: true
  target-url:
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/${{ inputs.repo }}/statuses/${{ inputs.sha }} \
        -f state='${{ inputs.state }}' \
        -f target_url='${{ inputs.target-url }}' \
        -f description='${{ inputs.description }}' \
        -f context='continuous-integration/github-actions'
